from django.utils.translation import ugettext_lazy as _

from base import conf

ENTERPRISE_MANAGER_GROUP_NAME = "Enterprise Manager"

PERMISSIONS = {
    # '': {
    #     'app_label': 'core',
    #     'model': 'core',
    #     'codename': 'code_name_for_permissions',
    # }
}

GROUPS = {
    'manager_enterprise': {
        "name": ENTERPRISE_MANAGER_GROUP_NAME,
        'permissions': [
            "change_enterprise",
            "add_product",
            "change_product",
            "delete_product",
            "add_discounts",
            "change_discounts",
            "delete_discounts"
        ]
    },
}

USER_CREATED = _("User created: {}")
USER_ALREADY_CREATED = _("User  already created: {}")


CATEGORY_PREFIX = "CATEGORY"

CATEGORY_VERBOSE_NAME = _("Category")
CATEGORY_VERBOSE_NAME_PLURAL = _("Category")

CATEGORY_LIST_URL_NAME = CATEGORY_PREFIX + conf.LIST_SUFFIX
CATEGORY_CREATE_URL_NAME = CATEGORY_PREFIX + conf.CREATE_SUFFIX
CATEGORY_DETAIL_URL_NAME = CATEGORY_PREFIX + conf.DETAIL_SUFFIX
CATEGORY_UPDATE_URL_NAME = CATEGORY_PREFIX + conf.UPDATE_SUFFIX
CATEGORY_DELETE_URL_NAME = CATEGORY_PREFIX + conf.DELETE_SUFFIX

CATEGORY_CREATED = _("Category created: {}")
CATEGORY_ALREADY_CREATED = _("Category already created: {}")

SUBCATEGORY_PREFIX = "SUBCATEGORY"

SUBCATEGORY_VERBOSE_NAME = _("Subcategory")
SUBCATEGORY_VERBOSE_NAME_PLURAL = _("Subcategory")

SUBCATEGORY_LIST_URL_NAME = SUBCATEGORY_PREFIX + conf.LIST_SUFFIX
SUBCATEGORY_CREATE_URL_NAME = SUBCATEGORY_PREFIX + conf.CREATE_SUFFIX
SUBCATEGORY_DETAIL_URL_NAME = SUBCATEGORY_PREFIX + conf.DETAIL_SUFFIX
SUBCATEGORY_UPDATE_URL_NAME = SUBCATEGORY_PREFIX + conf.UPDATE_SUFFIX
SUBCATEGORY_DELETE_URL_NAME = SUBCATEGORY_PREFIX + conf.DELETE_SUFFIX

SUBCATEGORY_CREATED = _("Subcategory created: {}")
SUBCATEGORY_ALREADY_CREATED = _("Subcategory  already created: {}")

ENTERPRISE_PREFIX = "ENTERPRISE"

ENTERPRISE_VERBOSE_NAME = _("Enterprise")
ENTERPRISE_VERBOSE_NAME_PLURAL = _("Enterprise")

ENTERPRISE_LIST_URL_NAME = ENTERPRISE_PREFIX + conf.LIST_SUFFIX
ENTERPRISE_CREATE_URL_NAME = ENTERPRISE_PREFIX + conf.CREATE_SUFFIX
ENTERPRISE_DETAIL_URL_NAME = ENTERPRISE_PREFIX + conf.DETAIL_SUFFIX
ENTERPRISE_UPDATE_URL_NAME = ENTERPRISE_PREFIX + conf.UPDATE_SUFFIX
ENTERPRISE_DELETE_URL_NAME = ENTERPRISE_PREFIX + conf.DELETE_SUFFIX
ENTERPRISE_ENTREPRENOURS_URL_NAME = ENTERPRISE_PREFIX + "_entreprenours"
ENTERPRISE_ENTREPRENOURS_CATEGORY_URL_NAME = ENTERPRISE_PREFIX + "_entreprenours_category"
ENTERPRISE_ENTREPRENOURS_SUBCATEGORY_URL_NAME = ENTERPRISE_PREFIX + "_entreprenours_subcategory"
ENTERPRISE_ENTREPRENOURS_SEARCH_URL_NAME = ENTERPRISE_PREFIX + "_entreprenours_search"
ENTERPRISE_ADD_PRODUCT_URL_NAME = ENTERPRISE_PREFIX + "_add_product"
ENTERPRISE_UPDATE_PRODUCT_URL_NAME = ENTERPRISE_PREFIX + "_update_product"
ENTERPRISE_DELETE_PRODUCT_URL_NAME = ENTERPRISE_PREFIX + "_delete_product"
ENTERPRISE_ADD_DISCOUNT_URL_NAME = ENTERPRISE_PREFIX + "_add_discount"
ENTERPRISE_DELETE_DISCOUNT_URL_NAME = ENTERPRISE_PREFIX + "_delete_discount"
ENTERPRISE_ADD_CONTACT_URL_NAME = ENTERPRISE_PREFIX + "_add_contact"
ENTERPRISE_LIST_CONTACT_URL_NAME = ENTERPRISE_PREFIX + "_list_contact"
ENTERPRISE_MY_ENTERPRISES = ENTERPRISE_PREFIX + "_my_enterprises"
ENTERPRISE_SLUG_URL_KWARG = "slug_enterprise"

ENTERPRISE_CREATED = _("Subcategory created: {}")
ENTERPRISE_ALREADY_CREATED = _("Subcategory  already created: {}")


PRODUCT_PREFIX = "PRODUCT"

PRODUCT_VERBOSE_NAME = _("Product")
PRODUCT_VERBOSE_NAME_PLURAL = _("Product")

PRODUCT_LIST_URL_NAME = PRODUCT_PREFIX + conf.LIST_SUFFIX
PRODUCT_CREATE_URL_NAME = PRODUCT_PREFIX + conf.CREATE_SUFFIX
PRODUCT_DETAIL_URL_NAME = PRODUCT_PREFIX + conf.DETAIL_SUFFIX
PRODUCT_UPDATE_URL_NAME = PRODUCT_PREFIX + conf.UPDATE_SUFFIX
PRODUCT_DELETE_URL_NAME = PRODUCT_PREFIX + conf.DELETE_SUFFIX
PRODUCT_SLUG_URL_KWARG = "slug_product"

DISCOUNTS_PREFIX = "DISCOUNTS"

DISCOUNTS_VERBOSE_NAME = _("Discounts")
DISCOUNTS_VERBOSE_NAME_PLURAL = _("Discounts")

DISCOUNTS_LIST_URL_NAME = DISCOUNTS_PREFIX + conf.LIST_SUFFIX
DISCOUNTS_CREATE_URL_NAME = DISCOUNTS_PREFIX + conf.CREATE_SUFFIX
DISCOUNTS_DETAIL_URL_NAME = DISCOUNTS_PREFIX + conf.DETAIL_SUFFIX
DISCOUNTS_UPDATE_URL_NAME = DISCOUNTS_PREFIX + conf.UPDATE_SUFFIX
DISCOUNTS_DELETE_URL_NAME = DISCOUNTS_PREFIX + conf.DELETE_SUFFIX
DISCOUNTS_SLUG_URL_KWARG = "slug_discount"
DISCOUNTS_QR_CODE_URL_NAME = DISCOUNTS_PREFIX + "_qr_code"

CONTACT_PREFIX = "CONTACT"

CONTACT_VERBOSE_NAME = _("Contact")
CONTACT_VERBOSE_NAME_PLURAL = _("Contact")

CONTACT_LIST_URL_NAME = CONTACT_PREFIX + conf.LIST_SUFFIX
CONTACT_CREATE_URL_NAME = CONTACT_PREFIX + conf.CREATE_SUFFIX
CONTACT_DETAIL_URL_NAME = CONTACT_PREFIX + conf.DETAIL_SUFFIX
CONTACT_UPDATE_URL_NAME = CONTACT_PREFIX + conf.UPDATE_SUFFIX
CONTACT_DELETE_URL_NAME = CONTACT_PREFIX + conf.DELETE_SUFFIX

MESSAGE_POSTED_SUCCESSFULLY = _("Message posted successfully")
