# Generated by Django 2.2 on 2019-05-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190425_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='keyboards',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
