# Generated by Django 2.2 on 2019-05-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190514_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='whatsapp_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
