# Generated by Django 2.2.2 on 2019-06-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_discounts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tel',
            field=models.CharField(default='', max_length=30),
        ),
    ]
