# Generated by Django 2.2 on 2019-06-07 23:10

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('url', models.TextField(default='')),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Enterprise')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, base.models.DisplayFieldsMixin),
        ),
    ]
